// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_services_default = defineTool({
  name: "get_services",
  title: "Get NavAura services",
  description: "Return NavAura AI's public service offerings, pricing tiers, and industry specializations.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const services = {
      company: "NavAura AI",
      tagline: "The Unified Intelligence for Modern Business",
      contact: "aura.usa@gmail.com",
      calendly: "https://calendly.com/auraai-usa/30min",
      services: [
        {
          name: "AI Automation",
          startingPrice: "$1,997/mo",
          description: "SOPs, lead generation, voice agents, and 24/7 follow-up sequences. Replaces a full sales team."
        },
        {
          name: "Technical SEO",
          startingPrice: "$1,497/mo",
          description: "Audits, schema, Core Web Vitals, backlinking, and content engine for page-1 rankings."
        },
        {
          name: "Full-Stack Development",
          startingPrice: "Custom quote",
          description: "Next.js + Supabase conversion-optimized sites, dashboards, and custom AI integrations."
        }
      ],
      industries: ["Med Spas", "Law Firms", "Fitness Studios"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
      structuredContent: services
    };
  }
});

// src/lib/mcp/tools/get-industry-details.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var get_industry_details_default = defineTool2({
  name: "get_industry_details",
  title: "Get industry details",
  description: "Return NavAura AI's pain points and AI solutions for a specific industry (med_spa, law_firm, or gym).",
  inputSchema: {
    industry: z.enum(["med_spa", "law_firm", "gym"]).describe("Industry key: med_spa, law_firm, or gym.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ industry }) => {
    const catalog = {
      med_spa: {
        title: "AI Automation for Med Spas",
        painPoints: [
          "Missed patient calls after hours",
          "No-shows and abandoned bookings",
          "Manual follow-up on consultations"
        ],
        aiSolutions: [
          "24/7 AI voice concierge that books appointments in real time",
          "Automated reminders and re-engagement sequences",
          "Lead qualification with instant CRM sync"
        ],
        proofPoint: "+40% Bookings, 98% Booking Accuracy"
      },
      law_firm: {
        title: "AI Automation for Law Firms",
        painPoints: [
          "Intake bottlenecks losing qualified cases",
          "Paralegal hours spent on repetitive triage",
          "Slow response killing high-intent leads"
        ],
        aiSolutions: [
          "AI intake agent that qualifies and schedules consultations",
          "Automated case-type routing and document requests",
          "2-second response SLA on inbound inquiries"
        ],
        proofPoint: "15 hours/week saved per firm"
      },
      gym: {
        title: "AI Automation for Fitness Studios",
        painPoints: [
          "Cold leads never convert to trial sessions",
          "Manual member retention and churn tracking",
          "No system for reactivating lapsed members"
        ],
        aiSolutions: [
          "AI SMS/voice concierge that books free trials automatically",
          "Retention flows triggered by attendance drops",
          "Win-back campaigns for lapsed members"
        ],
        proofPoint: "2x Lead Conversion"
      }
    };
    const data = catalog[industry];
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/submit-lead.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var submit_lead_default = defineTool3({
  name: "submit_lead",
  title: "Submit a lead",
  description: "Submit a new prospect lead to NavAura AI. Captures email (required), optional name, phone, industry, and a message.",
  inputSchema: {
    email: z2.string().email().max(255).describe("Prospect's email address."),
    name: z2.string().trim().max(120).optional().describe("Prospect's full name."),
    phone: z2.string().trim().max(40).optional().describe("Prospect's phone number."),
    industry: z2.enum(["med_spa", "law_firm", "gym", "other"]).optional().describe("Industry of the prospect."),
    message: z2.string().trim().max(2e3).optional().describe("Free-form message or context.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ email, name, phone, industry, message }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!supabaseUrl || !anonKey) {
      return {
        content: [{ type: "text", text: "Server not configured for lead submission." }],
        isError: true
      };
    }
    const supabase = createClient(supabaseUrl, anonKey, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("leads").insert({
      email,
      name: name ?? null,
      phone: phone ?? null,
      industry: industry ?? null,
      message: message ?? null,
      source: "MCP",
      lead_status: "new"
    }).select("id, email, created_at").single();
    if (error) {
      return {
        content: [{ type: "text", text: `Failed to submit lead: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Lead submitted. NavAura AI will follow up at ${email}. Book instantly: https://calendly.com/auraai-usa/30min`
        }
      ],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "navaura-ai-mcp",
  title: "NavAura AI",
  version: "0.1.0",
  instructions: "Public MCP server for NavAura AI. Use `get_services` for pricing and service info, `get_industry_details` for pain points and AI solutions per industry (med_spa, law_firm, gym), and `submit_lead` to register a new prospect. No authentication required.",
  tools: [get_services_default, get_industry_details_default, submit_lead_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
